/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/bookings/upcoming": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Предстоящие встречи: в одном списке показаны бронирования всех типов событий по возрастанию времени. */
        get: operations["AdminBookings_listUpcoming"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Список типов событий для админской части. */
        get: operations["AdminEventTypes_list"];
        put?: never;
        /** @description Создание типа события: id присваивается сервером, задаются название, описание и длительность в минутах. */
        post: operations["AdminEventTypes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Создание бронирования на выбранный свободный слот. */
        post: operations["Bookings_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Страница с видами брони: название, описание и длительность типа события. Доступна без входа. */
        get: operations["EventTypes_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types/{eventTypeId}/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Календарь свободных слотов в окне [from, to].
         *     Окно записи по умолчанию — ближайшие 14 дней от текущей даты.
         */
        get: operations["EventTypes_availability"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Окно доступности свободных слотов на ближайшие 14 дней от текущей даты. */
        AvailabilityWindow: {
            eventTypeId: string;
            /** Format: date */
            from: string;
            /** Format: date */
            to: string;
            days: components["schemas"]["DayAvailability"][];
        };
        /** @description Бронирование гостя на свободный слот. */
        Booking: {
            id: string;
            eventTypeId: string;
            guestName: string;
            /** Format: date-time */
            startAt: string;
            /** Format: date-time */
            endAt: string;
            /** Format: date-time */
            createdAt: string;
        };
        BookingList: {
            items: components["schemas"]["Booking"][];
        };
        ConflictError: {
            /** @enum {string} */
            code: "SLOT_OCCUPIED";
            message: string;
        };
        /** @description Данные для бронирования свободного слота без регистрации. */
        CreateBooking: {
            eventTypeId: string;
            guestName: string;
            /** Format: date-time */
            startAt: string;
        };
        /** @description Тело при создании типа события. id присваивается сервером. */
        CreateEventType: {
            name: string;
            description: string;
            /** Format: int32 */
            duration: number;
        };
        /** @description Доступные слоты для одного дня календаря. */
        DayAvailability: {
            /** Format: date */
            date: string;
            slots: components["schemas"]["Slot"][];
        };
        /** @description Тип события, создаваемый владельцем календаря: название, описание и длительность в минутах. */
        EventType: {
            id: string;
            name: string;
            description: string;
            /** Format: int32 */
            duration: number;
        };
        EventTypeList: {
            items: components["schemas"]["EventType"][];
        };
        NotFoundError: {
            /** @enum {string} */
            code: "NOT_FOUND";
            message: string;
        };
        /** @description Свободный слот в окне записи. */
        Slot: {
            /** Format: date-time */
            startAt: string;
            /** Format: date-time */
            endAt: string;
        };
        ValidationError: {
            /** @enum {string} */
            code: "VALIDATION_ERROR";
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AdminBookings_listUpcoming: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingList"];
                };
            };
        };
    };
    AdminEventTypes_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventTypeList"];
                };
            };
        };
    };
    AdminEventTypes_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEventType"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    Bookings_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBooking"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
            /** @description The request conflicts with the current state of the server. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictError"];
                };
            };
        };
    };
    EventTypes_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventTypeList"];
                };
            };
        };
    };
    EventTypes_availability: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path: {
                eventTypeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityWindow"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
}
